Fixed some API urls that have changed, and incorrect createUser 201 response behaviour
TransmitSecurity/ciam-expressjs-vanilla-samples pull request #109
Opened 2024-01-09 02:56 UTC by ian-sorbello-transmit

Working off the EU cloud, I found that the auth-hub sample had some incorrect pointers. 

1. Some APIs pointed to the US API cloud even when the Base URL was configured to EU
2. The createUser function in sign up expected a 200 response, otherwise views the sign up response as an error. CreateUser API now returns 201 as a successful create, so I've updated the code to expect 201
3. There were some missing /cis/ parts of the URL during callbacks on creating and logging in.

Overall, very minimal changes. There's a chance these updates may also be in another branch as part of general maintenance, so possibly this PR may not be needed.

2024-01-09 09:50 UTC, ts-ron commented on authentication-hub/backend/lib/management.js
> +    common.config.apis.logout; /* <-legacy. To be replaced with: common.config.apis.logout */
Can remove the comment now :)

2024-01-09 09:53 UTC, ts-ron commented on staging.env
> +# duplicate and rename this file to .env
Need to remove this file right? contains config and secrets

2024-01-09 09:55 UTC, ts-ron requested changes
LGTM - thanks :)
Need to git remove the config file (and add to .gitignore or something)

2024-01-09 23:36 UTC, ian-sorbello-transmit commented on staging.env
> +# duplicate and rename this file to .env
ooft. I explicitly didn't add the file into the commit, but it made its way in somehow. Yep, removing.

2024-01-09 23:43 UTC, ian-sorbello-transmit commented
@ts-ron - new update pushed. thanks for review. ps: this was my first git PR. It's fiddly working this stuff out for the first time..

2024-01-10 15:33 UTC, ts-ron approved these changes
LGTM 🥳

2024-04-12 07:17 UTC, merged