FLEXID-4280 Added menu for orchestration demo applications.  Added ba…
TransmitSecurity/ciam-expressjs-vanilla-samples pull request #93
Opened 2023-10-04 19:44 UTC by AvihaiApatoff

…ckend to support quick launch. Added onboarding simple flow sample. Added client integration simple flow sample.

2023-10-05 08:41 UTC, ts-ron commented on orchestration/menu.html
> +                    <img
@AvihaiApatoff I believe the "consume CSM" is not a journey we can demonstrate as a standalone.
Instead - I committed a small change where the "wait for ticket" page instructs you to open a link that contains the ticket-id in another browser. 
If this makes sense to you let's remove this button

2023-10-05 08:49 UTC, ts-ron requested changes
So overall looks great, and good you kept the core sample that also includes some backend logic and crypto binding based on forms. 
See my comment on the menu.html - on not exposing the `consume-csm` as a separate use case

2023-10-05 18:44 UTC, AvihaiApatoff commented
Removed the menu item for consume CSM. Some additional cosmetic fixes.

2023-10-06 06:49 UTC, ts-ron approved these changes
LGTM

2023-10-22 07:27 UTC, ShayKlig commented
@AvihaiApatoff @ts-ron i think we can close this one since we have merged the changes to the main-stage branch.

2023-10-22 09:18 UTC, ts-ron commented
> @AvihaiApatoff @ts-ron i think we can close this one since we have merged the changes to the main-stage branch.

@AvihaiApatoff do we want for now to make `main-stage` the de-facto main, until we stabilize? If so I agree w @ShayKlig

2023-10-23 20:14 UTC, AvihaiApatoff commented
> > @AvihaiApatoff @ts-ron i think we can close this one since we have merged the changes to the main-stage branch.
> 
> @AvihaiApatoff do we want for now to make `main-stage` the de-facto main, until we stabilize? If so I agree w @ShayKlig

I dont mind removing this PR. Any reason to keep main-stage and not merge it to main?

2023-10-25 01:27 UTC, closed without merging

2023-10-25 01:28 UTC, AvihaiApatoff commented
Content has been merged into main-stage for now.